### ISSUE TITLE
AttributeError: 'Ui_MainWindow' object has no attribute 'action_fangshe_encrypt'

### ISSUE THREAD

**Issue by nmweizi** [qianxiao996/CTF-Tools#1]
Traceback (most recent call last):
  File "CTF-Tools.py", line 1128, in <module>
    window = MainWindows()
  File "CTF-Tools.py", line 81, in __init__
    self.Ui.action_fangshe_encrypt.triggered.connect(lambda: self.encrypt(self.Ui.action_fangshe_encrypt.text()))
AttributeError: 'Ui_MainWindow' object has no attribute 'action_fangshe_encrypt'

python 3.8.3 64位，win10

**Comment by qianxiao996** [comment]
这是什么操作下产生的呢？一运行就这样了吗？我是3.7开发的，建议使用3.7试一下

**Comment by qianxiao996** [comment]
不好意思，有个文件忘记更新，你重新下载一下源码就可以了。

**Comment by nmweizi** [comment]
更新好了，thank.
