### ISSUE TITLE
【工具优化】使用问题合集？

### ISSUE THREAD

**Issue by mu0gua** [qianxiao996/CTF-Tools#10]
有很多场景会遇到批量base64或者其他的批量解码，是否可以考虑增加按行处理选项

**Comment by mu0gua** [comment]
工具安装后很多库都不太容易装，是否可以整个安装文档?

**Comment by qianxiao996** [comment]
已增加按行处理，但不建议数据太多。
已更新requirements.txt文件，直接使用pip安装即可。

**Comment by MangoYou** [comment]
安装py3base92==1.0.3.post1这个库报错
