### ISSUE TITLE
当Result中出现0xA,0xD时会有问题

### ISSUE THREAD

**Issue by euzenlee** [qianxiao996/CTF-Tools#3]
例如有 LVLVUXCABMFQEWINLUFQ6AS5L4FQ2WS5AJPAUCYNLJOVUXINLUEV6DQDBUEEM=== 需要用b32decode后对结果进行下一步操作，在Result中,（也许是将result复制到Source过程中），会将0xD转换为0xD0xA，字串失真，无法对结果执行进一步操作。

**Comment by euzenlee** [comment]
使用QTextEdit应该是无解的了，它内部会将\r转换为\n，QLineEdit则没有这个问题。

**Comment by qianxiao996** [comment]
已修复，感谢提出的问题。
