### ISSUE TITLE
输入源对大小写的要求比较混乱

### ISSUE THREAD

**Issue by euzenlee** [qianxiao996/CTF-Tools#4]
摩斯密码必须要求大写，而到了维吉尼亚则必须要小写，没错，摩斯的码表只有大写，但如果可以对源做一次upper() ，对用户是否更友好呢？
维吉尼亚的加密则有bug，大写的明文加密后无法解密出正确的文本，只有小写的明文加密后可以解密，但空格会丢失。然而我使用另外的工具加密一串混合大小写及空格的密文，你的程序是可以正确解密的。

**Comment by euzenlee** [comment]
b16decode 要求源必须为大写

**Comment by qianxiao996** [comment]
已修复，感谢提出的问题。
